excluded:
  - .tuist-bin
  - Tuist
  - Derived
  - Project.swift

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - vertical_whitespace_opening_braces
  - opening_brace

analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import

# rules that are commented out are explicitly opted out unless told otherwise
opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  #- anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  #- direct_return
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  #- explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  #- final_test_case # has been added to the source, but has not been released yet
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  #- function_default_parameter_at_end
  - identical_operands
  - implicitly_unwrapped_optional
  - implicit_return
  #- indentation_width # has conflicts with default xcode settings. use strg+i to indent correctly
  - joined_default_parameter
  - last_where
  #- legacy_multiple
  #- legacy_objc_type # not suitable do to third party libs
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_magic_numbers
  - number_separator
  - operator_usage_whitespace
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_swiftui_state
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  #- sorted_imports # see #1295 on github, conflicts with testable, also managed with swiftformat
  - static_operator
  - strict_fileprivate
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - unhandled_throwing_task
  - unowned_variable_capture
  - unneeded_parentheses_in_closure_argument
  #- vertical_parameter_alignment_on_call
  #- vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

file_header:
  required_pattern: |
                    \/\/
                    \/\/ Created by .*? on \d{1,2}\.\d{1,2}\.\d{2}\.
                    \/\/

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
  always_on_line_above:
    - "@discardableResult"

force_cast: error

force_try: error

function_body_length:
    warning: 150

legacy_hashing: error

identifier_name:
  min_length: 2
  max_length:
    warning: 60
    error: 80
  excluded:
    - id

multiline_arguments:
  first_argument_location: any_line
  only_enforce_after_first_closure_on_first_line: true
  
number_separator:
  minimum_length: 5

overridden_super_call:
  excluded:
    - setUp()
    - setUpWithError()
    - tearDown()
    - tearDownWithError()
  
private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

type_name:
  min_length: 3
  max_length:
    warning: 70
    error: 80
  allowed_symbols:
    - "_"

inclusive_language:
  override_allowed_terms: [whitelist]

trailing_closure:
  only_single_muted_parameter: true

cyclomatic_complexity:
  ignores_case_statements: true

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400
