import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: Constants.projectName, 
    projects: ["."], 
    generationOptions: .options(
            autogeneratedWorkspaceSchemes: .disabled
        )
    )