name: checks

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CI: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
          version: 2024.6.3
          install: true
          cache: true
    - uses: mobiledevops/secret-to-file-action@v1
      with:
          base64-encoded-secret: ${{ secrets.DEBUG_XCCONFIG }}
          filename: "Debug.xcconfig"
          working-directory: ".configurations/.xcconfig"
    - uses: mobiledevops/secret-to-file-action@v1
      with:
          base64-encoded-secret: ${{ secrets.RELEASE_XCCONFIG }}
          filename: "Release.xcconfig"
          working-directory: ".configurations/.xcconfig"
    - uses: mobiledevops/secret-to-file-action@v1
      with:
          base64-encoded-secret: ${{ secrets.SHARED_XCCONFIG }}
          filename: "Shared.xcconfig"
          working-directory: ".configurations/.xcconfig"
    - run: make prepare
    - run: make build

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
          version: 2024.6.3
          install: true
          cache: true
    - uses: mobiledevops/secret-to-file-action@v1
      with:
          base64-encoded-secret: ${{ secrets.DEBUG_XCCONFIG }}
          filename: "Debug.xcconfig"
          is-executable: true
          working-directory: ".configurations/.xcconfig"
    - uses: mobiledevops/secret-to-file-action@v1
      with:
          base64-encoded-secret: ${{ secrets.RELEASE_XCCONFIG }}
          filename: "Release.xcconfig"
          is-executable: true
          working-directory: ".configurations/.xcconfig"
    - uses: mobiledevops/secret-to-file-action@v1
      with:
          base64-encoded-secret: ${{ secrets.SHARED_XCCONFIG }}
          filename: "Shared.xcconfig"
          is-executable: true
          working-directory: ".configurations/.xcconfig"
    - run: make prepare
    run: make test

  lint-swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
          version: 2024.6.3
          install: true
          cache: true
    - run: make ci-lint-swiftlint

  lint-swiftformat:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
          version: 2024.6.3
          install: true
          cache: true
    - run: make ci-lint-swiftformat
